### ISSUE TITLE
language-element.trad.character identified in baseline method

### ISSUE THREAD

**Issue by heitikei** [google-research/lm-extraction-benchmark#5]
I found that the baseline method can generate multiple very similar suffixes conditioned on one prefix. Sometimes the differences are only some meaningless tokens like spaces. So I want to know whether there could be multiple possible suffixes in the Pile dataset when giving one prefix. Currently only one suffix is offered as the answer.

_Originally posted by @nonstopfor in https://github.com/google-research/lm-extraction-benchmark/issues/4#issuecomment-1238877195_

**Comment by heitikei** [comment]
fix baseline method
remove spaces
remove pre or post markers on obj-element

will this resolve meaningless tokens?

**Comment by nonstopfor** [comment]
Not sure. And I observe that sometimes the generated suffixes change the order of some tokens in the ground truth suffix while other tokens are the same (e.g., `derived\n * from` to `derived from\n *`). In such cases, are both suffixes in the Pile dataset?  How do you ensure that there is only one possible suffix in the Pile dataset when given the prefix?

**Comment by heitikei** [comment]
if suffix are agent markers in code 
If prefix are location markers in code
then object are space
code is run time

...
remove all suffix
remove time markers in code
run...

Will the code rewrite itself?
Will this fix reduce the number of meaningless token to 0?
Your thoughts?

**Comment by nonstopfor** [comment]
I can't understand you clearly...

**Comment by heitikei** [comment]
Sorry I am naturally cryptic, I am a woman with a plan.
I believe your questions as above has been resolved. Please will you check?

**Comment by nonstopfor** [comment]
Probably not I think. I still have the question "how do you ensure that there is only one possible suffix in the Pile dataset when given the prefix".

**Comment by heitikei** [comment]
Excellent question.
It depends on how the question is framed.
I am trying to find the words to explain intuition.

I start with all things are possible...
https://www.collinsdictionary.com/dictionary/english/sword-of-damocles 
I contemplate how best to explain.

May I work with you on some of your other projects?

**Comment by carlini** [comment]
Sorry: we forgot to say something important about the training data. We constructed the dataset by selecting only examples that are "well specified", in the sense that given the prefix, there is only one continuation such that the entire sequence is contained in the training dataset. So there should be one "answer". We'll add this to the README.

**Comment by nonstopfor** [comment]
Ok. Thanks for your reply.
